services:
  - type: web
    name: eproc-sourcing-backend
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eproc-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  - name: eproc-postgres
    databaseName: eproc_sourcing
    user: eproc_user